name: "Setup Python environment"
description: "Setup Python environment, install dependencies, and verify the environment"

author: "Thibaut Durand"

branding:
  icon: "python"
  color: "blue"

inputs:
  python-version:
    default: "3.13"
    description: "Python version to use"
    required: false
    type: string
  package-name:
    default: ""
    description: "Optional package name to install"
    required: false
    type: string
  package-version:
    default: ""
    description: "Optional package version to install"
    required: false
    type: string
  install-args:
    default: ""
    description: "Optional arguments when installing dependencies"
    required: false
    type: string

runs:
  using: "composite"
  steps:
    # Install uv package manager and activate Python environment
    - name: Install uv and set the python version
      uses: astral-sh/setup-uv@v7
      with:
        python-version: ${{ inputs.python-version }}
        activate-environment: true

    # Verify uv and python are available in PATH
    - name: Verify uv and python installation
      shell: bash
      run: |
        which uv
        which python

    # Install invoke task runner for development commands
    - name: Install invoke
      shell: bash
      run: |
        make install-invoke

    # Install project dependencies (with optional arguments like --docs-deps, --no-optional-deps)
    - name: Install dependencies
      shell: bash
      run: |
        inv install ${{ inputs.install-args }}

    # Install a specific version of a package (used for dependency compatibility testing)
    - name: Install valid package version
      if: ${{ inputs.package-name != '' }}
      uses: durandtibo/uv-install-package-action@v0.1.1
      with:
        package-name: ${{ inputs.package-name }}
        package-version: ${{ inputs.package-version }}
        python-version: ${{ inputs.python-version }}

    # Display Python configuration for debugging
    - name: Show python config
      shell: bash
      run: |
        inv show-python-config

    # Display all installed packages for debugging
    - name: Show installed packages
      shell: bash
      run: |
        inv show-installed-packages

    # Display dependency tree with version specifiers
    - name: Show dependency tree
      shell: bash
      run: |
        uv pip tree --show-version-specifiers

    # Verify environment integrity (continue even if there are conflicts)
    - name: Verify the current environment
      shell: bash
      continue-on-error: true
      run: |
        uv pip check
