name: "Setup Python environment"
description:
  "Setup Python environment using uv, install dependencies, and verify the
  environment with comprehensive diagnostics"

author: "Thibaut Durand"

branding:
  icon: "layers"
  color: "blue"

inputs:
  python-version:
    default: "3.13"
    description:
      "Python version to use (e.g., '3.13', '3.12', '3.11', '3.10'). Defaults
      to Python 3.13."
    required: false
  package-name:
    default: ""
    description:
      "Optional package name to install for dependency compatibility testing.
      Use with 'package-version' to test specific versions. Leave empty to
      skip."
    required: false
  package-version:
    default: ""
    description: "Optional package version to install (e.g., '1.0.0'). Only used
      when 'package-name' is specified. Leave empty to install latest version."
    required: false
  install-args:
    default: ""
    description:
      "Optional arguments passed to 'inv install' command (e.g., '--all-extras',
      '--no-dev', custom flags supported by your tasks.py install task)."
    required: false

runs:
  using: "composite"
  steps:
    # Step 1: Install uv package manager and configure Python environment
    # Uses the astral-sh/setup-uv action which:
    # - Installs uv (ultra-fast Python package installer and resolver)
    # - Sets up the specified Python version
    # - Activates the Python environment so subsequent steps can use 'python' and 'pip'
    - name: Install uv and set the python version
      uses: astral-sh/setup-uv@v7
      with:
        python-version: ${{ inputs.python-version }}
        activate-environment: true

    # Step 2: Verify that uv and python are properly installed and available in PATH
    # This is a safety check to ensure the environment setup succeeded
    # Outputs the full paths to both executables for debugging
    - name: Verify uv and python installation
      shell: bash
      run: |
        which uv
        which python

    # Step 3: Install invoke task runner
    # Invoke is used to run project management tasks defined in tasks.py
    - name: Install invoke
      shell: bash
      run: |
        uv pip install "invoke>=2.2.0"

    # Step 4: Install project dependencies using the invoke install task
    # This typically runs 'uv sync --frozen' and 'uv pip install -e .'
    # Optional install-args can be passed to customize the installation
    # (e.g., --all-extras to install optional dependencies)
    - name: Install dependencies
      shell: bash
      run: |
        inv install ${{ inputs.install-args }}

    # Step 5 (Optional): Install a specific package version for compatibility testing
    # This step only runs if package-name is provided
    # Useful for testing your project against different versions of a dependency
    # Example: Test against numpy 1.24.0, 1.25.0, etc. in a matrix strategy
    - name: Install valid package version
      if: ${{ inputs.package-name != '' }}
      uses: durandtibo/uv-install-package-action@v0.1.1
      with:
        package-name: ${{ inputs.package-name }}
        package-version: ${{ inputs.package-version }}
        python-version: ${{ inputs.python-version }}

    # Step 6: Display Python configuration for debugging and verification
    # Shows:
    # - All Python versions managed by uv
    # - The active Python interpreter
    # - Full path to the python executable
    # Useful for troubleshooting version-related issues
    - name: Show python config
      shell: bash
      run: |
        inv show-python-config

    # Step 7: Display all installed packages with their versions
    # Provides a complete inventory of the Python environment
    # Helpful for debugging dependency issues and verifying installations
    - name: Show installed packages
      shell: bash
      run: |
        inv show-installed-packages

    # Step 8: Display the dependency tree with version constraints
    # Shows the full dependency graph including:
    # - Direct dependencies
    # - Transitive (indirect) dependencies
    # - Version specifiers (e.g., >=1.0.0, <2.0)
    # Useful for understanding dependency relationships and conflicts
    - name: Show dependency tree
      shell: bash
      run: |
        uv pip tree --show-version-specifiers

    # Step 9: Verify environment integrity
    # Runs 'uv pip check' to detect:
    # - Missing dependencies
    # - Version conflicts
    # - Broken installations
    # Uses continue-on-error so the workflow continues even with conflicts
    # (conflicts are logged for debugging but don't fail the build)
    - name: Verify the current environment
      shell: bash
      continue-on-error: true
      run: |
        uv pip check
